name: entrance_test
description: A new Flutter project.
publish_to: "none"
version: 18.1.20+31

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.0.0
  fluttertoast: ^8.2.5
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  open_file_plus: ^3.4.1+1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  talker_dio_logger: ^4.2.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon-app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon-app.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/icon-app.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon-app.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/icon-app.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
